
package Model.Agente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "srvAgente", targetNamespace = "http://Agente.Service/", wsdlLocation = "http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvAgente?wsdl")
public class SrvAgente_Service
    extends Service
{

    private final static URL SRVAGENTE_WSDL_LOCATION;
    private final static WebServiceException SRVAGENTE_EXCEPTION;
    private final static QName SRVAGENTE_QNAME = new QName("http://Agente.Service/", "srvAgente");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvAgente?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRVAGENTE_WSDL_LOCATION = url;
        SRVAGENTE_EXCEPTION = e;
    }

    public SrvAgente_Service() {
        super(__getWsdlLocation(), SRVAGENTE_QNAME);
    }

    public SrvAgente_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRVAGENTE_QNAME, features);
    }

    public SrvAgente_Service(URL wsdlLocation) {
        super(wsdlLocation, SRVAGENTE_QNAME);
    }

    public SrvAgente_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRVAGENTE_QNAME, features);
    }

    public SrvAgente_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvAgente_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SrvAgente
     */
    @WebEndpoint(name = "srvAgentePort")
    public SrvAgente getSrvAgentePort() {
        return super.getPort(new QName("http://Agente.Service/", "srvAgentePort"), SrvAgente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SrvAgente
     */
    @WebEndpoint(name = "srvAgentePort")
    public SrvAgente getSrvAgentePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Agente.Service/", "srvAgentePort"), SrvAgente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRVAGENTE_EXCEPTION!= null) {
            throw SRVAGENTE_EXCEPTION;
        }
        return SRVAGENTE_WSDL_LOCATION;
    }

}
