
package Model.Pago;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "srvPago", targetNamespace = "http://Pago.Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SrvPago {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarPago", targetNamespace = "http://Pago.Service/", className = "Model.Pago.InsertarPago")
    @ResponseWrapper(localName = "insertarPagoResponse", targetNamespace = "http://Pago.Service/", className = "Model.Pago.InsertarPagoResponse")
    @Action(input = "http://Pago.Service/srvPago/insertarPagoRequest", output = "http://Pago.Service/srvPago/insertarPagoResponse")
    public int insertarPago(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarPago", targetNamespace = "http://Pago.Service/", className = "Model.Pago.ActualizarPago")
    @ResponseWrapper(localName = "actualizarPagoResponse", targetNamespace = "http://Pago.Service/", className = "Model.Pago.ActualizarPagoResponse")
    @Action(input = "http://Pago.Service/srvPago/actualizarPagoRequest", output = "http://Pago.Service/srvPago/actualizarPagoResponse")
    public int actualizarPago(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @return
     *     returns java.util.List<Model.Pago.Pago>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPago", targetNamespace = "http://Pago.Service/", className = "Model.Pago.ListarPago")
    @ResponseWrapper(localName = "listarPagoResponse", targetNamespace = "http://Pago.Service/", className = "Model.Pago.ListarPagoResponse")
    @Action(input = "http://Pago.Service/srvPago/listarPagoRequest", output = "http://Pago.Service/srvPago/listarPagoResponse")
    public List<Pago> listarPago();

    /**
     * 
     * @param arg0
     * @return
     *     returns Model.Pago.Pago
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarPago", targetNamespace = "http://Pago.Service/", className = "Model.Pago.BuscarPago")
    @ResponseWrapper(localName = "buscarPagoResponse", targetNamespace = "http://Pago.Service/", className = "Model.Pago.BuscarPagoResponse")
    @Action(input = "http://Pago.Service/srvPago/buscarPagoRequest", output = "http://Pago.Service/srvPago/buscarPagoResponse")
    public Pago buscarPago(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarPago", targetNamespace = "http://Pago.Service/", className = "Model.Pago.EliminarPago")
    @ResponseWrapper(localName = "eliminarPagoResponse", targetNamespace = "http://Pago.Service/", className = "Model.Pago.EliminarPagoResponse")
    @Action(input = "http://Pago.Service/srvPago/eliminarPagoRequest", output = "http://Pago.Service/srvPago/eliminarPagoResponse")
    public int eliminarPago(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
