
package Model.Pago;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "srvPago", targetNamespace = "http://Pago.Service/", wsdlLocation = "http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvPago?wsdl")
public class SrvPago_Service
    extends Service
{

    private final static URL SRVPAGO_WSDL_LOCATION;
    private final static WebServiceException SRVPAGO_EXCEPTION;
    private final static QName SRVPAGO_QNAME = new QName("http://Pago.Service/", "srvPago");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvPago?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRVPAGO_WSDL_LOCATION = url;
        SRVPAGO_EXCEPTION = e;
    }

    public SrvPago_Service() {
        super(__getWsdlLocation(), SRVPAGO_QNAME);
    }

    public SrvPago_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRVPAGO_QNAME, features);
    }

    public SrvPago_Service(URL wsdlLocation) {
        super(wsdlLocation, SRVPAGO_QNAME);
    }

    public SrvPago_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRVPAGO_QNAME, features);
    }

    public SrvPago_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvPago_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SrvPago
     */
    @WebEndpoint(name = "srvPagoPort")
    public SrvPago getSrvPagoPort() {
        return super.getPort(new QName("http://Pago.Service/", "srvPagoPort"), SrvPago.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SrvPago
     */
    @WebEndpoint(name = "srvPagoPort")
    public SrvPago getSrvPagoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Pago.Service/", "srvPagoPort"), SrvPago.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRVPAGO_EXCEPTION!= null) {
            throw SRVPAGO_EXCEPTION;
        }
        return SRVPAGO_WSDL_LOCATION;
    }

}
