
package Model.Usuario;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "srvUsuario", targetNamespace = "http://Usuario.Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SrvUsuario {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns Model.Usuario.Login
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autenticarUsuario", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.AutenticarUsuario")
    @ResponseWrapper(localName = "autenticarUsuarioResponse", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.AutenticarUsuarioResponse")
    @Action(input = "http://Usuario.Service/srvUsuario/autenticarUsuarioRequest", output = "http://Usuario.Service/srvUsuario/autenticarUsuarioResponse")
    public Login autenticarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarUsuario", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.ActualizarUsuario")
    @ResponseWrapper(localName = "actualizarUsuarioResponse", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.ActualizarUsuarioResponse")
    @Action(input = "http://Usuario.Service/srvUsuario/actualizarUsuarioRequest", output = "http://Usuario.Service/srvUsuario/actualizarUsuarioResponse")
    public int actualizarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarUsuario", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.EliminarUsuario")
    @ResponseWrapper(localName = "eliminarUsuarioResponse", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.EliminarUsuarioResponse")
    @Action(input = "http://Usuario.Service/srvUsuario/eliminarUsuarioRequest", output = "http://Usuario.Service/srvUsuario/eliminarUsuarioResponse")
    public int eliminarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarUsuario", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.InsertarUsuario")
    @ResponseWrapper(localName = "insertarUsuarioResponse", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.InsertarUsuarioResponse")
    @Action(input = "http://Usuario.Service/srvUsuario/insertarUsuarioRequest", output = "http://Usuario.Service/srvUsuario/insertarUsuarioResponse")
    public int insertarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @return
     *     returns java.util.List<Model.Usuario.Usuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarUsuarios", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.ListarUsuarios")
    @ResponseWrapper(localName = "listarUsuariosResponse", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.ListarUsuariosResponse")
    @Action(input = "http://Usuario.Service/srvUsuario/listarUsuariosRequest", output = "http://Usuario.Service/srvUsuario/listarUsuariosResponse")
    public List<Usuario> listarUsuarios();

    /**
     * 
     * @param arg0
     * @return
     *     returns Model.Usuario.Usuario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarUsuario", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.BuscarUsuario")
    @ResponseWrapper(localName = "buscarUsuarioResponse", targetNamespace = "http://Usuario.Service/", className = "Model.Usuario.BuscarUsuarioResponse")
    @Action(input = "http://Usuario.Service/srvUsuario/buscarUsuarioRequest", output = "http://Usuario.Service/srvUsuario/buscarUsuarioResponse")
    public Usuario buscarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
