
package Model.Vehiculo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "srvVehiculo", targetNamespace = "http://Vehiculo.Service/", wsdlLocation = "http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvVehiculo?wsdl")
public class SrvVehiculo_Service
    extends Service
{

    private final static URL SRVVEHICULO_WSDL_LOCATION;
    private final static WebServiceException SRVVEHICULO_EXCEPTION;
    private final static QName SRVVEHICULO_QNAME = new QName("http://Vehiculo.Service/", "srvVehiculo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvVehiculo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRVVEHICULO_WSDL_LOCATION = url;
        SRVVEHICULO_EXCEPTION = e;
    }

    public SrvVehiculo_Service() {
        super(__getWsdlLocation(), SRVVEHICULO_QNAME);
    }

    public SrvVehiculo_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRVVEHICULO_QNAME, features);
    }

    public SrvVehiculo_Service(URL wsdlLocation) {
        super(wsdlLocation, SRVVEHICULO_QNAME);
    }

    public SrvVehiculo_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRVVEHICULO_QNAME, features);
    }

    public SrvVehiculo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvVehiculo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SrvVehiculo
     */
    @WebEndpoint(name = "srvVehiculoPort")
    public SrvVehiculo getSrvVehiculoPort() {
        return super.getPort(new QName("http://Vehiculo.Service/", "srvVehiculoPort"), SrvVehiculo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SrvVehiculo
     */
    @WebEndpoint(name = "srvVehiculoPort")
    public SrvVehiculo getSrvVehiculoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Vehiculo.Service/", "srvVehiculoPort"), SrvVehiculo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRVVEHICULO_EXCEPTION!= null) {
            throw SRVVEHICULO_EXCEPTION;
        }
        return SRVVEHICULO_WSDL_LOCATION;
    }

}
