
package Model.Vehiculo;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "srvVehiculo", targetNamespace = "http://Vehiculo.Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SrvVehiculo {


    /**
     * 
     * @param marca
     * @param idVehiculo
     * @param modelo
     * @param placa
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarVehiculo", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.InsertarVehiculo")
    @ResponseWrapper(localName = "insertarVehiculoResponse", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.InsertarVehiculoResponse")
    @Action(input = "http://Vehiculo.Service/srvVehiculo/insertarVehiculoRequest", output = "http://Vehiculo.Service/srvVehiculo/insertarVehiculoResponse")
    public int insertarVehiculo(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        String idVehiculo,
        @WebParam(name = "placa", targetNamespace = "")
        String placa,
        @WebParam(name = "marca", targetNamespace = "")
        String marca,
        @WebParam(name = "modelo", targetNamespace = "")
        String modelo);

    /**
     * 
     * @param placa
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarVehiculo", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.EliminarVehiculo")
    @ResponseWrapper(localName = "eliminarVehiculoResponse", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.EliminarVehiculoResponse")
    @Action(input = "http://Vehiculo.Service/srvVehiculo/eliminarVehiculoRequest", output = "http://Vehiculo.Service/srvVehiculo/eliminarVehiculoResponse")
    public int eliminarVehiculo(
        @WebParam(name = "placa", targetNamespace = "")
        String placa);

    /**
     * 
     * @return
     *     returns java.util.List<Model.Vehiculo.Vehiculo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarVehiculos", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.ListarVehiculos")
    @ResponseWrapper(localName = "listarVehiculosResponse", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.ListarVehiculosResponse")
    @Action(input = "http://Vehiculo.Service/srvVehiculo/listarVehiculosRequest", output = "http://Vehiculo.Service/srvVehiculo/listarVehiculosResponse")
    public List<Vehiculo> listarVehiculos();

    /**
     * 
     * @param placa
     * @return
     *     returns Model.Vehiculo.Vehiculo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarVehiculo", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.BuscarVehiculo")
    @ResponseWrapper(localName = "buscarVehiculoResponse", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.BuscarVehiculoResponse")
    @Action(input = "http://Vehiculo.Service/srvVehiculo/buscarVehiculoRequest", output = "http://Vehiculo.Service/srvVehiculo/buscarVehiculoResponse")
    public Vehiculo buscarVehiculo(
        @WebParam(name = "placa", targetNamespace = "")
        String placa);

    /**
     * 
     * @param marca
     * @param idVehiculo
     * @param modelo
     * @param placa
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarVehiculo", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.ActualizarVehiculo")
    @ResponseWrapper(localName = "actualizarVehiculoResponse", targetNamespace = "http://Vehiculo.Service/", className = "Model.Vehiculo.ActualizarVehiculoResponse")
    @Action(input = "http://Vehiculo.Service/srvVehiculo/actualizarVehiculoRequest", output = "http://Vehiculo.Service/srvVehiculo/actualizarVehiculoResponse")
    public int actualizarVehiculo(
        @WebParam(name = "idVehiculo", targetNamespace = "")
        String idVehiculo,
        @WebParam(name = "placa", targetNamespace = "")
        String placa,
        @WebParam(name = "marca", targetNamespace = "")
        String marca,
        @WebParam(name = "modelo", targetNamespace = "")
        String modelo);

}
