
package Model.Sancion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "srvSancion", targetNamespace = "http://Sancion.Service/", wsdlLocation = "http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvSancion?wsdl")
public class SrvSancion_Service
    extends Service
{

    private final static URL SRVSANCION_WSDL_LOCATION;
    private final static WebServiceException SRVSANCION_EXCEPTION;
    private final static QName SRVSANCION_QNAME = new QName("http://Sancion.Service/", "srvSancion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvSancion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRVSANCION_WSDL_LOCATION = url;
        SRVSANCION_EXCEPTION = e;
    }

    public SrvSancion_Service() {
        super(__getWsdlLocation(), SRVSANCION_QNAME);
    }

    public SrvSancion_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRVSANCION_QNAME, features);
    }

    public SrvSancion_Service(URL wsdlLocation) {
        super(wsdlLocation, SRVSANCION_QNAME);
    }

    public SrvSancion_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRVSANCION_QNAME, features);
    }

    public SrvSancion_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvSancion_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SrvSancion
     */
    @WebEndpoint(name = "srvSancionPort")
    public SrvSancion getSrvSancionPort() {
        return super.getPort(new QName("http://Sancion.Service/", "srvSancionPort"), SrvSancion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SrvSancion
     */
    @WebEndpoint(name = "srvSancionPort")
    public SrvSancion getSrvSancionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Sancion.Service/", "srvSancionPort"), SrvSancion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRVSANCION_EXCEPTION!= null) {
            throw SRVSANCION_EXCEPTION;
        }
        return SRVSANCION_WSDL_LOCATION;
    }

}
