
package Model.Infraccion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "srvInfraccion", targetNamespace = "http://Infraccion.Service/", wsdlLocation = "http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvInfraccion?wsdl")
public class SrvInfraccion_Service
    extends Service
{

    private final static URL SRVINFRACCION_WSDL_LOCATION;
    private final static WebServiceException SRVINFRACCION_EXCEPTION;
    private final static QName SRVINFRACCION_QNAME = new QName("http://Infraccion.Service/", "srvInfraccion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvInfraccion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRVINFRACCION_WSDL_LOCATION = url;
        SRVINFRACCION_EXCEPTION = e;
    }

    public SrvInfraccion_Service() {
        super(__getWsdlLocation(), SRVINFRACCION_QNAME);
    }

    public SrvInfraccion_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRVINFRACCION_QNAME, features);
    }

    public SrvInfraccion_Service(URL wsdlLocation) {
        super(wsdlLocation, SRVINFRACCION_QNAME);
    }

    public SrvInfraccion_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRVINFRACCION_QNAME, features);
    }

    public SrvInfraccion_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvInfraccion_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SrvInfraccion
     */
    @WebEndpoint(name = "srvInfraccionPort")
    public SrvInfraccion getSrvInfraccionPort() {
        return super.getPort(new QName("http://Infraccion.Service/", "srvInfraccionPort"), SrvInfraccion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SrvInfraccion
     */
    @WebEndpoint(name = "srvInfraccionPort")
    public SrvInfraccion getSrvInfraccionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Infraccion.Service/", "srvInfraccionPort"), SrvInfraccion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRVINFRACCION_EXCEPTION!= null) {
            throw SRVINFRACCION_EXCEPTION;
        }
        return SRVINFRACCION_WSDL_LOCATION;
    }

}
