
package Model.Infraccion;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "srvInfraccion", targetNamespace = "http://Infraccion.Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SrvInfraccion {


    /**
     * 
     * @return
     *     returns java.util.List<Model.Infraccion.Infraccion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarInfracciones", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.ListarInfracciones")
    @ResponseWrapper(localName = "listarInfraccionesResponse", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.ListarInfraccionesResponse")
    @Action(input = "http://Infraccion.Service/srvInfraccion/listarInfraccionesRequest", output = "http://Infraccion.Service/srvInfraccion/listarInfraccionesResponse")
    public List<Infraccion> listarInfracciones();

    /**
     * 
     * @param idInfraccion
     * @return
     *     returns Model.Infraccion.Infraccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarInfraccion", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.BuscarInfraccion")
    @ResponseWrapper(localName = "buscarInfraccionResponse", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.BuscarInfraccionResponse")
    @Action(input = "http://Infraccion.Service/srvInfraccion/buscarInfraccionRequest", output = "http://Infraccion.Service/srvInfraccion/buscarInfraccionResponse")
    public Infraccion buscarInfraccion(
        @WebParam(name = "idInfraccion", targetNamespace = "")
        String idInfraccion);

    /**
     * 
     * @param descripcion
     * @param idInfraccion
     * @param multa
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarInfraccion", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.InsertarInfraccion")
    @ResponseWrapper(localName = "insertarInfraccionResponse", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.InsertarInfraccionResponse")
    @Action(input = "http://Infraccion.Service/srvInfraccion/insertarInfraccionRequest", output = "http://Infraccion.Service/srvInfraccion/insertarInfraccionResponse")
    public int insertarInfraccion(
        @WebParam(name = "idInfraccion", targetNamespace = "")
        String idInfraccion,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "multa", targetNamespace = "")
        int multa);

    /**
     * 
     * @param descripcion
     * @param idInfraccion
     * @param multa
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarInfraccion", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.ActualizarInfraccion")
    @ResponseWrapper(localName = "actualizarInfraccionResponse", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.ActualizarInfraccionResponse")
    @Action(input = "http://Infraccion.Service/srvInfraccion/actualizarInfraccionRequest", output = "http://Infraccion.Service/srvInfraccion/actualizarInfraccionResponse")
    public int actualizarInfraccion(
        @WebParam(name = "idInfraccion", targetNamespace = "")
        String idInfraccion,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "multa", targetNamespace = "")
        int multa);

    /**
     * 
     * @param idInfraccion
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarInfraccion", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.EliminarInfraccion")
    @ResponseWrapper(localName = "eliminarInfraccionResponse", targetNamespace = "http://Infraccion.Service/", className = "Model.Infraccion.EliminarInfraccionResponse")
    @Action(input = "http://Infraccion.Service/srvInfraccion/eliminarInfraccionRequest", output = "http://Infraccion.Service/srvInfraccion/eliminarInfraccionResponse")
    public int eliminarInfraccion(
        @WebParam(name = "idInfraccion", targetNamespace = "")
        String idInfraccion);

}
