
package Model.Conductor;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "srvConductor", targetNamespace = "http://Conductor.Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SrvConductor {


    /**
     * 
     * @return
     *     returns java.util.List<Model.Conductor.Conductor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarConductores", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.ListarConductores")
    @ResponseWrapper(localName = "listarConductoresResponse", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.ListarConductoresResponse")
    @Action(input = "http://Conductor.Service/srvConductor/listarConductoresRequest", output = "http://Conductor.Service/srvConductor/listarConductoresResponse")
    public List<Conductor> listarConductores();

    /**
     * 
     * @param idLicencia
     * @return
     *     returns Model.Conductor.Conductor
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarConductor", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.BuscarConductor")
    @ResponseWrapper(localName = "buscarConductorResponse", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.BuscarConductorResponse")
    @Action(input = "http://Conductor.Service/srvConductor/buscarConductorRequest", output = "http://Conductor.Service/srvConductor/buscarConductorResponse")
    public Conductor buscarConductor(
        @WebParam(name = "idLicencia", targetNamespace = "")
        String idLicencia);

    /**
     * 
     * @param idLicencia
     * @param idVehiculo
     * @param nombre
     * @param edad
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarConductor", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.ActualizarConductor")
    @ResponseWrapper(localName = "actualizarConductorResponse", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.ActualizarConductorResponse")
    @Action(input = "http://Conductor.Service/srvConductor/actualizarConductorRequest", output = "http://Conductor.Service/srvConductor/actualizarConductorResponse")
    public int actualizarConductor(
        @WebParam(name = "idLicencia", targetNamespace = "")
        String idLicencia,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "edad", targetNamespace = "")
        int edad,
        @WebParam(name = "idVehiculo", targetNamespace = "")
        String idVehiculo);

    /**
     * 
     * @param idLicencia
     * @param idVehiculo
     * @param nombre
     * @param edad
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarConductor", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.InsertarConductor")
    @ResponseWrapper(localName = "insertarConductorResponse", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.InsertarConductorResponse")
    @Action(input = "http://Conductor.Service/srvConductor/insertarConductorRequest", output = "http://Conductor.Service/srvConductor/insertarConductorResponse")
    public int insertarConductor(
        @WebParam(name = "idLicencia", targetNamespace = "")
        String idLicencia,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "edad", targetNamespace = "")
        int edad,
        @WebParam(name = "idVehiculo", targetNamespace = "")
        String idVehiculo);

    /**
     * 
     * @param idLicencia
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarConductor", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.EliminarConductor")
    @ResponseWrapper(localName = "eliminarConductorResponse", targetNamespace = "http://Conductor.Service/", className = "Model.Conductor.EliminarConductorResponse")
    @Action(input = "http://Conductor.Service/srvConductor/eliminarConductorRequest", output = "http://Conductor.Service/srvConductor/eliminarConductorResponse")
    public int eliminarConductor(
        @WebParam(name = "idLicencia", targetNamespace = "")
        String idLicencia);

}
