
package Model.Conductor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "srvConductor", targetNamespace = "http://Conductor.Service/", wsdlLocation = "http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvConductor?wsdl")
public class SrvConductor_Service
    extends Service
{

    private final static URL SRVCONDUCTOR_WSDL_LOCATION;
    private final static WebServiceException SRVCONDUCTOR_EXCEPTION;
    private final static QName SRVCONDUCTOR_QNAME = new QName("http://Conductor.Service/", "srvConductor");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServices_Infracciones.IntelliJ-1.0-SNAPSHOT/srvConductor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRVCONDUCTOR_WSDL_LOCATION = url;
        SRVCONDUCTOR_EXCEPTION = e;
    }

    public SrvConductor_Service() {
        super(__getWsdlLocation(), SRVCONDUCTOR_QNAME);
    }

    public SrvConductor_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRVCONDUCTOR_QNAME, features);
    }

    public SrvConductor_Service(URL wsdlLocation) {
        super(wsdlLocation, SRVCONDUCTOR_QNAME);
    }

    public SrvConductor_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRVCONDUCTOR_QNAME, features);
    }

    public SrvConductor_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvConductor_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SrvConductor
     */
    @WebEndpoint(name = "srvConductorPort")
    public SrvConductor getSrvConductorPort() {
        return super.getPort(new QName("http://Conductor.Service/", "srvConductorPort"), SrvConductor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SrvConductor
     */
    @WebEndpoint(name = "srvConductorPort")
    public SrvConductor getSrvConductorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Conductor.Service/", "srvConductorPort"), SrvConductor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRVCONDUCTOR_EXCEPTION!= null) {
            throw SRVCONDUCTOR_EXCEPTION;
        }
        return SRVCONDUCTOR_WSDL_LOCATION;
    }

}
